import type { Team } from '../types/game';

export interface TeamTemplate {
  name: string;
  div: number;
  country: string;
  state: string;
  cont: Team['continent'];
  str: number;
}

export const FIRST_NAMES = ['João', 'Pedro', 'Lucas', 'Mateus', 'Gabriel', 'Enzo', 'Valentim', 'Arthur', 'Carlos', 'Eduardo', 'Luis', 'Fernando', 'Rafael', 'Diego', 'Marcelo', 'Alex', 'Bruno', 'Thiago', 'Felipe', 'Gustavo', 'John', 'David', 'Michael', 'Chris', 'James', 'Robert', 'William', 'Joseph', 'Thomas', 'Charles'];
export const LAST_NAMES = ['Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Alves', 'Pereira', 'Lima', 'Gomes', 'Costa', 'Ribeiro', 'Martins', 'Carvalho', 'Almeida', 'Lopes', 'Soares', 'Fernandes', 'Vieira', 'Gomes', 'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez'];

export const BRAZIL_STATE_OVERRIDES: Record<string, string> = {
  'FLAMENGO': 'RJ',
  'PALMEIRAS': 'SP',
  'CRUZEIRO': 'MG',
  'MIRASSOL': 'SP',
  'FLUMINENSE': 'RJ',
  'BAHIA': 'BA',
  'BOTAFOGO': 'RJ',
  'SAO PAULO': 'SP',
  'RED BULL BRAGANTINO': 'SP',
  'CORINTHIANS': 'SP',
  'GREMIO': 'RS',
  'VASCO': 'RJ',
  'CLUBE ATLETICO MINEIRO': 'MG',
  'SANTOS': 'SP',
  'VITORIA': 'BA',
  'INTERNACIONAL': 'RS',
  'CORITIBA': 'PR',
  'CHAPECOENSE': 'SC',
  'REMO': 'PA',
  'CEARA': 'CE',
  'FORTALEZA': 'CE',
  'JUVENTUDE': 'RS',
  'SPORT': 'PE',
  'PONTE PRETA': 'SP',
  'LONDRINA': 'PR',
  'NAUTICO': 'PE',
  'SAO BERNARDO': 'SP',
  'CRICIUMA': 'SC',
  'GOIAS': 'GO',
  'NOVORIZONTINO': 'SP',
  'CRB': 'AL',
  'AVAI': 'SC',
  'CUIABA': 'MT',
  'VILA NOVA': 'GO',
  'TOMBENSE': 'MG',
  'CSA': 'AL',
  'INDEPENDENCIA': 'AC',
  'GALVEZ': 'AC',
  'ASA': 'AL',
  'CSE': 'AL',
  'TREM': 'AP',
  'ORATORIO': 'AP',
  'MANAUS': 'AM',
  'JACUIPENSE': 'BA',
  'TIROL': 'CE',
  'FERROVIARIO': 'CE',
  'MARACANA': 'CE',
  'GAMA': 'DF',
  'CRAC': 'GO',
  'ABECAT': 'GO',
  'INHUMAS': 'GO',
  'IMPERATRIZ': 'MA',
  'IAPE': 'MA',
  'PRIMAVERA': 'MT',
  'MIXTO': 'MT',
  'PANTANAL': 'MS',
  'BETIM': 'MG',
  'DEMOCRATA GV': 'MG',
  'UBERLANDIA': 'MG',
  'TUNA LUSO': 'PA',
  'SOUSA': 'PB',
  'SERRA BRANCA': 'PB',
  'AZURIZ': 'PR',
  'CIANORTE': 'PR',
  'MAGUARY': 'PE',
  'DECISAO': 'PE',
  'PIAUI': 'PI',
  'MADUREIRA': 'RJ',
  'LAGUNA': 'RN',
  'BRASIL DE PELOTAS': 'RS',
  'GUARANY DE BAGE': 'RS',
  'PORTO VELHO': 'RO',
  'GUAPORE': 'RO',
  'GAS': 'RR',
  'JOINVILLE': 'SC',
  'SANTA CATARINA': 'SC',
  'BLUMENAU': 'SC',
  'PORTUGUESA': 'SP',
  'VELO CLUBE': 'SP',
  'NOROESTE': 'SP',
  'LAGARTO': 'SE',
  'SERGIPE': 'SE',
  'ARAGUAINA': 'TO',
  'TOCANTINOPOLIS': 'TO',
  'MANAUARA': 'AM',
  'CEILANDIA': 'DF',
  'GOIATUBA': 'GO',
  'CENTRAL': 'PE',
  'ALTOS': 'PI',
  'MARICA': 'RJ',
  'BRASILIENSE': 'DF',
  'POUSO ALEGRE': 'MG',
  'HUMAITA': 'AC',
  'IGUATU': 'CE',
  'REAL NOROESTE': 'ES',
  'TREZE': 'PB',
  'MOTO CLUB': 'MA',
  'PARNAHYBA': 'PI',
};

export const TEAM_TEMPLATES = [
  // BRASIL
  { name: 'Flamengo', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Palmeiras', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Cruzeiro', div: 1, country: 'BR', state: '', cont: 'SA', str: 87 },
  { name: 'Mirassol', div: 1, country: 'BR', state: '', cont: 'SA', str: 85 },
  { name: 'Fluminense', div: 1, country: 'BR', state: '', cont: 'SA', str: 82 },
  { name: 'Bahia', div: 1, country: 'BR', state: '', cont: 'SA', str: 84 },
  { name: 'Botafogo', div: 1, country: 'BR', state: '', cont: 'SA', str: 82 },
  { name: 'São Paulo', div: 1, country: 'BR', state: '', cont: 'SA', str: 84 },
  { name: 'Red Bull Bragantino', div: 1, country: 'BR', state: '', cont: 'SA', str: 82 },
  { name: 'Corinthians', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Grêmio', div: 1, country: 'BR', state: '', cont: 'SA', str: 86 },
  { name: 'Vasco', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Clube Atlético Mineiro', div: 1, country: 'BR', state: '', cont: 'SA', str: 84 },
  { name: 'Santos', div: 1, country: 'BR', state: '', cont: 'SA', str: 84 },
  { name: 'Vitória', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Internacional', div: 1, country: 'BR', state: '', cont: 'SA', str: 85 },
  { name: 'Coritiba', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Athletico-PR', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Chapecoense', div: 1, country: 'BR', state: '', cont: 'SA', str: 85 },
  { name: 'Remo', div: 1, country: 'BR', state: '', cont: 'SA', str: 83 },
  { name: 'Ceará', div: 2, country: 'BR', state: '', cont: 'SA', str: 73 },
  { name: 'Fortaleza', div: 2, country: 'BR', state: '', cont: 'SA', str: 76 },
  { name: 'Juventude', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Sport', div: 2, country: 'BR', state: '', cont: 'SA', str: 72 },
  { name: 'Ponte Preta', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Londrina', div: 2, country: 'BR', state: '', cont: 'SA', str: 73 },
  { name: 'Náutico', div: 2, country: 'BR', state: '', cont: 'SA', str: 72 },
  { name: 'São Bernardo', div: 2, country: 'BR', state: '', cont: 'SA', str: 76 },
  { name: 'Criciúma', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Goiás', div: 2, country: 'BR', state: '', cont: 'SA', str: 75 },
  { name: 'Novorizontino', div: 2, country: 'BR', state: '', cont: 'SA', str: 73 },
  { name: 'CRB', div: 2, country: 'BR', state: '', cont: 'SA', str: 73 },
  { name: 'Avaí', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Cuiabá', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Atlético-GO', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Operário-PR', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Vila Nova', div: 2, country: 'BR', state: '', cont: 'SA', str: 77 },
  { name: 'América-MG', div: 2, country: 'BR', state: '', cont: 'SA', str: 76 },
  { name: 'Athletic-MG', div: 2, country: 'BR', state: '', cont: 'SA', str: 73 },
  { name: 'Botafogo-SP', div: 2, country: 'BR', state: '', cont: 'SA', str: 74 },
  { name: 'Inter de Limeira-SP', div: 3, country: 'BR', state: '', cont: 'SA', str: 62 },
  { name: 'Floresta-CE', div: 3, country: 'BR', state: '', cont: 'SA', str: 64 },
  { name: 'Ituano-SP', div: 3, country: 'BR', state: '', cont: 'SA', str: 62 },
  { name: 'Anápolis-GO', div: 3, country: 'BR', state: '', cont: 'SA', str: 65 },
  { name: 'Brusque-SC', div: 3, country: 'BR', state: '', cont: 'SA', str: 66 },
  { name: 'Caxias-RS', div: 3, country: 'BR', state: '', cont: 'SA', str: 62 },
  { name: 'Confiança-SE', div: 3, country: 'BR', state: '', cont: 'SA', str: 65 },
  { name: 'Amazonas-AM', div: 3, country: 'BR', state: '', cont: 'SA', str: 66 },
  { name: 'Maranhão-MA', div: 3, country: 'BR', state: '', cont: 'SA', str: 67 },
  { name: 'Guarani-SP', div: 3, country: 'BR', state: '', cont: 'SA', str: 67 },
  { name: 'Volta Redonda-RJ', div: 3, country: 'BR', state: '', cont: 'SA', str: 65 },
  { name: 'Paysandu-PA', div: 3, country: 'BR', state: '', cont: 'SA', str: 65 },
  { name: 'Maringá-PR', div: 3, country: 'BR', state: '', cont: 'SA', str: 67 },
  { name: 'Ferroviária-SP', div: 3, country: 'BR', state: '', cont: 'SA', str: 63 },
  { name: 'Ypiranga-RS', div: 3, country: 'BR', state: '', cont: 'SA', str: 66 },
  { name: 'Figueirense-SC', div: 3, country: 'BR', state: '', cont: 'SA', str: 64 },
  { name: 'Santa Cruz-PE', div: 3, country: 'BR', state: '', cont: 'SA', str: 64 },
  { name: 'Itabaiana-SE', div: 3, country: 'BR', state: '', cont: 'SA', str: 62 },
  { name: 'Botafogo-PB', div: 3, country: 'BR', state: '', cont: 'SA', str: 64 },
  { name: 'Barra-SC', div: 3, country: 'BR', state: '', cont: 'SA', str: 65 },
  { name: 'ABC', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Retrô', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Tombense', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'CSA', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Independência', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Galvez', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'ASA', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'CSE', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Trem', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Oratório', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Nacional-AM', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Manaus', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Atlético-BA', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Jacuipense', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Porto-BA', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Tirol', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Ferroviário', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Maracanã', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Capital-DF', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Gama', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Rio Branco-ES', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Vitória-ES', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'CRAC', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Abecat', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Inhumas', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Imperatriz', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'IAPE', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Primavera-MT', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Mixto-MT', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Operário-MS', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Pantanal', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Betim', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Democrata GV', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Uberlândia', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Tuna Luso', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Águia de Marabá', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Sousa', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Serra Branca', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Azuriz', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'São Joseense', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Cianorte', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Maguary', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Decisão', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Piauí', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Fluminense-PI', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Madureira', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'America-RJ', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Sampaio Corrêa-RJ', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Laguna', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'América-RN', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Brasil de Pelotas', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'São Luiz', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Guarany de Bagé', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Porto Velho', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Guaporé', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'GAS', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Monte Roraima', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Joinville', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Santa Catarina', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Blumenau', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Portuguesa', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Velo Clube', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Noroeste', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'XV de Piracicaba', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Lagarto', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Sergipe', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Araguaína', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Tocantinópolis', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Manauara', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Juazeirense', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Ceilândia', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Aparecidense', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Goiatuba', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Sampaio Corrêa-MA', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Luverdense', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'FC Cascavel', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Central', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Altos', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Maricá', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'São José-RS', div: 4, country: 'BR', state: '', cont: 'SA', str: 56 },
  { name: 'Marcílio Dias', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Água Santa', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Nova Iguaçu', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Brasiliense', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Pouso Alegre', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Portuguesa-RJ', div: 4, country: 'BR', state: '', cont: 'SA', str: 57 },
  { name: 'Humaitá', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'São Raimundo-RR', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Iguatu', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'União Rondonópolis', div: 4, country: 'BR', state: '', cont: 'SA', str: 55 },
  { name: 'Real Noroeste', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Treze', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Atlético-CE', div: 4, country: 'BR', state: '', cont: 'SA', str: 53 },
  { name: 'Operário VG', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },
  { name: 'Moto Club', div: 4, country: 'BR', state: '', cont: 'SA', str: 54 },
  { name: 'Parnahyba', div: 4, country: 'BR', state: '', cont: 'SA', str: 52 },

  // ARGENTINA
  { name: 'River Plate', div: 1, country: 'AR', state: '', cont: 'SA', str: 84 },
  { name: 'Boca Juniors', div: 1, country: 'AR', state: '', cont: 'SA', str: 84 },
  { name: 'Racing Club', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Independiente', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'San Lorenzo', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Huracán', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Vélez Sarsfield', div: 1, country: 'AR', state: '', cont: 'SA', str: 84 },
  { name: 'Estudiantes LP', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Gimnasia LP', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Rosario Central', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Newell\'s Old Boys', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Lanús', div: 1, country: 'AR', state: '', cont: 'SA', str: 84 },
  { name: 'Banfield', div: 1, country: 'AR', state: '', cont: 'SA', str: 80 },
  { name: 'Defensa y Justicia', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Talleres', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Belgrano', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Instituto', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Central Córdoba', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Atlético Tucumán', div: 1, country: 'AR', state: '', cont: 'SA', str: 84 },
  { name: 'Unión', div: 1, country: 'AR', state: '', cont: 'SA', str: 81 },
  { name: 'Platense', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Tigre', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Argentinos Juniors', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Barracas Central', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Sarmiento', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Independiente Rivadavia', div: 1, country: 'AR', state: '', cont: 'SA', str: 83 },
  { name: 'Deportivo Riestra', div: 1, country: 'AR', state: '', cont: 'SA', str: 82 },
  { name: 'Aldosivi', div: 1, country: 'AR', state: '', cont: 'SA', str: 79 },
  { name: 'Gimnasia Mendoza', div: 1, country: 'AR', state: '', cont: 'SA', str: 81 },
  { name: 'Estudiantes Río Cuarto', div: 1, country: 'AR', state: '', cont: 'SA', str: 81 },
  { name: 'All Boys', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Almagro', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Almirante Brown', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Atlanta', div: 2, country: 'AR', state: '', cont: 'SA', str: 73 },
  { name: 'Chacarita Juniors', div: 2, country: 'AR', state: '', cont: 'SA', str: 71 },
  { name: 'Chaco For Ever', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Colón', div: 2, country: 'AR', state: '', cont: 'SA', str: 74 },
  { name: 'Defensores de Belgrano', div: 2, country: 'AR', state: '', cont: 'SA', str: 73 },
  { name: 'Defensores Unidos', div: 2, country: 'AR', state: '', cont: 'SA', str: 74 },
  { name: 'Deportivo Madryn', div: 2, country: 'AR', state: '', cont: 'SA', str: 74 },
  { name: 'Deportivo Maipú', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Deportivo Morón', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Estudiantes BA', div: 2, country: 'AR', state: '', cont: 'SA', str: 70 },
  { name: 'Ferro Carril Oeste', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Gimnasia y Tiro', div: 2, country: 'AR', state: '', cont: 'SA', str: 70 },
  { name: 'Gimnasia Jujuy', div: 2, country: 'AR', state: '', cont: 'SA', str: 70 },
  { name: 'Los Andes', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Mitre', div: 2, country: 'AR', state: '', cont: 'SA', str: 73 },
  { name: 'Nueva Chicago', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Patronato', div: 2, country: 'AR', state: '', cont: 'SA', str: 73 },
  { name: 'Quilmes', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Racing Córdoba', div: 2, country: 'AR', state: '', cont: 'SA', str: 74 },
  { name: 'San Martín Tucumán', div: 2, country: 'AR', state: '', cont: 'SA', str: 71 },
  { name: 'San Martín San Juan', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'San Miguel', div: 2, country: 'AR', state: '', cont: 'SA', str: 70 },
  { name: 'San Telmo', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Temperley', div: 2, country: 'AR', state: '', cont: 'SA', str: 73 },
  { name: 'Tristán Suárez', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Agropecuario', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Brown de Adrogué', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Güemes', div: 2, country: 'AR', state: '', cont: 'SA', str: 70 },
  { name: 'Arsenal de Sarandí', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Ciudad de Bolívar', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },
  { name: 'Central Norte', div: 2, country: 'AR', state: '', cont: 'SA', str: 72 },
  { name: 'Acassuso', div: 2, country: 'AR', state: '', cont: 'SA', str: 74 },
  { name: 'Colegiales', div: 2, country: 'AR', state: '', cont: 'SA', str: 69 },

  // URUGUAI
  { name: 'Peñarol', div: 1, country: 'UY', state: '', cont: 'SA', str: 78 },
  { name: 'Nacional', div: 1, country: 'UY', state: '', cont: 'SA', str: 80 },
  { name: 'Defensor Sporting', div: 1, country: 'UY', state: '', cont: 'SA', str: 77 },
  { name: 'Danubio', div: 1, country: 'UY', state: '', cont: 'SA', str: 76 },
  { name: 'Liverpool Montevideo', div: 1, country: 'UY', state: '', cont: 'SA', str: 79 },
  { name: 'Montevideo City Torque', div: 1, country: 'UY', state: '', cont: 'SA', str: 76 },
  { name: 'Boston River', div: 1, country: 'UY', state: '', cont: 'SA', str: 76 },
  { name: 'Cerro Largo', div: 1, country: 'UY', state: '', cont: 'SA', str: 79 },
  { name: 'Cerro', div: 1, country: 'UY', state: '', cont: 'SA', str: 79 },
  { name: 'Juventud', div: 1, country: 'UY', state: '', cont: 'SA', str: 78 },
  { name: 'Albion', div: 1, country: 'UY', state: '', cont: 'SA', str: 78 },
  { name: 'Progreso', div: 1, country: 'UY', state: '', cont: 'SA', str: 79 },
  { name: 'Central Español', div: 1, country: 'UY', state: '', cont: 'SA', str: 80 },
  { name: 'Deportivo Maldonado', div: 1, country: 'UY', state: '', cont: 'SA', str: 75 },
  { name: 'Racing Montevideo', div: 1, country: 'UY', state: '', cont: 'SA', str: 75 },
  { name: 'Wanderers', div: 1, country: 'UY', state: '', cont: 'SA', str: 76 },
  { name: 'Atenas', div: 2, country: 'UY', state: '', cont: 'SA', str: 67 },
  { name: 'Cerrito', div: 2, country: 'UY', state: '', cont: 'SA', str: 67 },
  { name: 'Colón', div: 2, country: 'UY', state: '', cont: 'SA', str: 70 },
  { name: 'Fénix', div: 2, country: 'UY', state: '', cont: 'SA', str: 68 },
  { name: 'Huracán', div: 2, country: 'UY', state: '', cont: 'SA', str: 70 },
  { name: 'La Luz', div: 2, country: 'UY', state: '', cont: 'SA', str: 66 },
  { name: 'Miramar Misiones', div: 2, country: 'UY', state: '', cont: 'SA', str: 68 },
  { name: 'Oriental', div: 2, country: 'UY', state: '', cont: 'SA', str: 65 },
  { name: 'Paysandú', div: 2, country: 'UY', state: '', cont: 'SA', str: 67 },
  { name: 'Plaza Colonia', div: 2, country: 'UY', state: '', cont: 'SA', str: 68 },
  { name: 'Rentistas', div: 2, country: 'UY', state: '', cont: 'SA', str: 68 },
  { name: 'River Plate Montevideo', div: 2, country: 'UY', state: '', cont: 'SA', str: 66 },
  { name: 'Tacuarembó', div: 2, country: 'UY', state: '', cont: 'SA', str: 65 },
  { name: 'Uruguay Montevideo', div: 2, country: 'UY', state: '', cont: 'SA', str: 70 },
  { name: 'Basáñez', div: 3, country: 'UY', state: '', cont: 'SA', str: 56 },
  { name: 'Bella Vista', div: 3, country: 'UY', state: '', cont: 'SA', str: 59 },
  { name: 'Alto Perú', div: 3, country: 'UY', state: '', cont: 'SA', str: 56 },
  { name: 'Villa Teresa', div: 3, country: 'UY', state: '', cont: 'SA', str: 57 },
  { name: 'Canadian', div: 3, country: 'UY', state: '', cont: 'SA', str: 60 },
  { name: 'Deportivo Colonia', div: 3, country: 'UY', state: '', cont: 'SA', str: 60 },
  { name: 'Cooper', div: 3, country: 'UY', state: '', cont: 'SA', str: 59 },
  { name: 'Villa Española', div: 3, country: 'UY', state: '', cont: 'SA', str: 56 },
  { name: 'Huracán Buceo', div: 3, country: 'UY', state: '', cont: 'SA', str: 60 },
  { name: 'Huracán Paso de la Arena', div: 3, country: 'UY', state: '', cont: 'SA', str: 58 },
  { name: 'Mar de Fondo', div: 3, country: 'UY', state: '', cont: 'SA', str: 58 },
  { name: 'Paysandú FC', div: 3, country: 'UY', state: '', cont: 'SA', str: 55 },
  { name: 'Platense Montevideo', div: 3, country: 'UY', state: '', cont: 'SA', str: 56 },
  { name: 'Rocha', div: 3, country: 'UY', state: '', cont: 'SA', str: 57 },
  { name: 'Sud América', div: 3, country: 'UY', state: '', cont: 'SA', str: 56 },

  // PARAGUAI
  { name: 'Olimpia', div: 1, country: 'PY', state: '', cont: 'SA', str: 73 },
  { name: 'Cerro Porteño', div: 1, country: 'PY', state: '', cont: 'SA', str: 72 },
  { name: 'Libertad', div: 1, country: 'PY', state: '', cont: 'SA', str: 77 },
  { name: 'Guaraní', div: 1, country: 'PY', state: '', cont: 'SA', str: 76 },
  { name: 'Nacional', div: 1, country: 'PY', state: '', cont: 'SA', str: 77 },
  { name: 'Sportivo Luqueño', div: 1, country: 'PY', state: '', cont: 'SA', str: 77 },
  { name: 'Sportivo Ameliano', div: 1, country: 'PY', state: '', cont: 'SA', str: 72 },
  { name: 'Sportivo Trinidense', div: 1, country: 'PY', state: '', cont: 'SA', str: 74 },
  { name: '2 de Mayo', div: 1, country: 'PY', state: '', cont: 'SA', str: 77 },
  { name: 'Rubio Ñu', div: 1, country: 'PY', state: '', cont: 'SA', str: 76 },
  { name: 'Deportivo Recoleta', div: 1, country: 'PY', state: '', cont: 'SA', str: 76 },
  { name: 'San Lorenzo', div: 1, country: 'PY', state: '', cont: 'SA', str: 75 },
  { name: 'Sol de América', div: 2, country: 'PY', state: '', cont: 'SA', str: 62 },
  { name: 'Tacuary', div: 2, country: 'PY', state: '', cont: 'SA', str: 67 },
  { name: 'Independiente FBC', div: 2, country: 'PY', state: '', cont: 'SA', str: 64 },
  { name: 'Fernando de la Mora', div: 2, country: 'PY', state: '', cont: 'SA', str: 66 },
  { name: 'Sportivo Carapeguá', div: 2, country: 'PY', state: '', cont: 'SA', str: 64 },
  { name: '3 de Noviembre', div: 2, country: 'PY', state: '', cont: 'SA', str: 64 },
  { name: 'Atlético Tembetary', div: 2, country: 'PY', state: '', cont: 'SA', str: 66 },
  { name: 'Benjamín Aceval', div: 2, country: 'PY', state: '', cont: 'SA', str: 66 },
  { name: 'Deportivo Capiatá', div: 2, country: 'PY', state: '', cont: 'SA', str: 66 },
  { name: 'Deportivo Santaní', div: 2, country: 'PY', state: '', cont: 'SA', str: 63 },
  { name: 'Encarnación FC', div: 2, country: 'PY', state: '', cont: 'SA', str: 63 },
  { name: 'General Caballero JLM', div: 2, country: 'PY', state: '', cont: 'SA', str: 65 },
  { name: 'Guaireña', div: 2, country: 'PY', state: '', cont: 'SA', str: 65 },
  { name: 'Resistencia', div: 2, country: 'PY', state: '', cont: 'SA', str: 63 },
  { name: 'Paraguarí AC', div: 2, country: 'PY', state: '', cont: 'SA', str: 67 },
  { name: '12 de Junio', div: 2, country: 'PY', state: '', cont: 'SA', str: 64 },
  { name: 'Atlético Colegiales', div: 3, country: 'PY', state: '', cont: 'SA', str: 55 },
  { name: 'Cristóbal Colón', div: 3, country: 'PY', state: '', cont: 'SA', str: 55 },
  { name: '3 de Febrero', div: 3, country: 'PY', state: '', cont: 'SA', str: 55 },
  { name: '24 de Septiembre', div: 3, country: 'PY', state: '', cont: 'SA', str: 52 },
  { name: 'Olimpia de Itá', div: 3, country: 'PY', state: '', cont: 'SA', str: 56 },
  { name: 'Sport Colombia', div: 3, country: 'PY', state: '', cont: 'SA', str: 54 },
  { name: 'Sportivo Limpeño', div: 3, country: 'PY', state: '', cont: 'SA', str: 52 },
  { name: 'Sportivo Iteño', div: 3, country: 'PY', state: '', cont: 'SA', str: 57 },
  { name: 'Presidente Hayes', div: 3, country: 'PY', state: '', cont: 'SA', str: 52 },
  { name: 'Tacuary B', div: 3, country: 'PY', state: '', cont: 'SA', str: 52 },
  { name: 'Benjamín Aceval B', div: 3, country: 'PY', state: '', cont: 'SA', str: 53 },
  { name: 'Deportivo Recoleta B', div: 3, country: 'PY', state: '', cont: 'SA', str: 54 },
  { name: 'Cerro Corá', div: 3, country: 'PY', state: '', cont: 'SA', str: 54 },
  { name: 'General Caballero ZC', div: 3, country: 'PY', state: '', cont: 'SA', str: 52 },
  { name: '12 de Octubre de Itauguá', div: 3, country: 'PY', state: '', cont: 'SA', str: 57 },
  { name: 'Pilcomayo', div: 3, country: 'PY', state: '', cont: 'SA', str: 53 },
  { name: 'Silvio Pettirossi', div: 3, country: 'PY', state: '', cont: 'SA', str: 53 },

  // CHILE
  { name: 'Colo-Colo', div: 1, country: 'CL', state: '', cont: 'SA', str: 76 },
  { name: 'Universidad de Chile', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Universidad Católica', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Coquimbo Unido', div: 1, country: 'CL', state: '', cont: 'SA', str: 74 },
  { name: 'Unión Española', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Unión La Calera', div: 1, country: 'CL', state: '', cont: 'SA', str: 76 },
  { name: 'Huachipato', div: 1, country: 'CL', state: '', cont: 'SA', str: 77 },
  { name: 'Palestino', div: 1, country: 'CL', state: '', cont: 'SA', str: 76 },
  { name: 'Cobresal', div: 1, country: 'CL', state: '', cont: 'SA', str: 76 },
  { name: 'O\'Higgins', div: 1, country: 'CL', state: '', cont: 'SA', str: 75 },
  { name: 'Everton de Viña del Mar', div: 1, country: 'CL', state: '', cont: 'SA', str: 76 },
  { name: 'Ñublense', div: 1, country: 'CL', state: '', cont: 'SA', str: 77 },
  { name: 'Deportes Iquique', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Universidad de Concepción', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Audax Italiano', div: 1, country: 'CL', state: '', cont: 'SA', str: 75 },
  { name: 'Deportes Limache', div: 1, country: 'CL', state: '', cont: 'SA', str: 73 },
  { name: 'Cobreloa', div: 2, country: 'CL', state: '', cont: 'SA', str: 66 },
  { name: 'Santiago Wanderers', div: 2, country: 'CL', state: '', cont: 'SA', str: 63 },
  { name: 'Magallanes', div: 2, country: 'CL', state: '', cont: 'SA', str: 68 },
  { name: 'San Marcos de Arica', div: 2, country: 'CL', state: '', cont: 'SA', str: 67 },
  { name: 'Curicó Unido', div: 2, country: 'CL', state: '', cont: 'SA', str: 63 },
  { name: 'Rangers de Talca', div: 2, country: 'CL', state: '', cont: 'SA', str: 64 },
  { name: 'Deportes Antofagasta', div: 2, country: 'CL', state: '', cont: 'SA', str: 67 },
  { name: 'Deportes Copiapó', div: 2, country: 'CL', state: '', cont: 'SA', str: 67 },
  { name: 'Deportes Recoleta', div: 2, country: 'CL', state: '', cont: 'SA', str: 63 },
  { name: 'Deportes Santa Cruz', div: 2, country: 'CL', state: '', cont: 'SA', str: 65 },
  { name: 'Deportes Temuco', div: 2, country: 'CL', state: '', cont: 'SA', str: 66 },
  { name: 'Deportes Puerto Montt', div: 2, country: 'CL', state: '', cont: 'SA', str: 66 },
  { name: 'Unión San Felipe', div: 2, country: 'CL', state: '', cont: 'SA', str: 65 },
  { name: 'Santiago Morning', div: 2, country: 'CL', state: '', cont: 'SA', str: 68 },
  { name: 'San Luis de Quillota', div: 2, country: 'CL', state: '', cont: 'SA', str: 64 },
  { name: 'Barnechea', div: 2, country: 'CL', state: '', cont: 'SA', str: 68 },

  // ESTADOS UNIDOS
  { name: 'Atlanta United', div: 1, country: 'US', state: '', cont: 'NA', str: 78 },
  { name: 'Austin FC', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'Charlotte FC', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'Chicago Fire', div: 1, country: 'US', state: '', cont: 'NA', str: 78 },
  { name: 'FC Cincinnati', div: 1, country: 'US', state: '', cont: 'NA', str: 76 },
  { name: 'Colorado Rapids', div: 1, country: 'US', state: '', cont: 'NA', str: 75 },
  { name: 'Columbus Crew', div: 1, country: 'US', state: '', cont: 'NA', str: 75 },
  { name: 'D.C. United', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'FC Dallas', div: 1, country: 'US', state: '', cont: 'NA', str: 78 },
  { name: 'Houston Dynamo', div: 1, country: 'US', state: '', cont: 'NA', str: 76 },
  { name: 'Inter Miami', div: 1, country: 'US', state: '', cont: 'NA', str: 75 },
  { name: 'LA Galaxy', div: 1, country: 'US', state: '', cont: 'NA', str: 80 },
  { name: 'Los Angeles FC', div: 1, country: 'US', state: '', cont: 'NA', str: 80 },
  { name: 'Minnesota United', div: 1, country: 'US', state: '', cont: 'NA', str: 75 },
  { name: 'CF Montréal', div: 1, country: 'US', state: '', cont: 'NA', str: 80 },
  { name: 'Nashville SC', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'New England Revolution', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'New York City FC', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'New York Red Bulls', div: 1, country: 'US', state: '', cont: 'NA', str: 76 },
  { name: 'Orlando City', div: 1, country: 'US', state: '', cont: 'NA', str: 75 },
  { name: 'Philadelphia Union', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'Portland Timbers', div: 1, country: 'US', state: '', cont: 'NA', str: 78 },
  { name: 'Real Salt Lake', div: 1, country: 'US', state: '', cont: 'NA', str: 76 },
  { name: 'San Diego FC', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'San Jose Earthquakes', div: 1, country: 'US', state: '', cont: 'NA', str: 80 },
  { name: 'Seattle Sounders', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'Sporting Kansas City', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'St. Louis City SC', div: 1, country: 'US', state: '', cont: 'NA', str: 79 },
  { name: 'Toronto FC', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'Vancouver Whitecaps', div: 1, country: 'US', state: '', cont: 'NA', str: 77 },
  { name: 'Birmingham Legion', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'Charleston Battery', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'Colorado Springs Switchbacks', div: 2, country: 'US', state: '', cont: 'NA', str: 68 },
  { name: 'Detroit City FC', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'El Paso Locomotive', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'FC Tulsa', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Hartford Athletic', div: 2, country: 'US', state: '', cont: 'NA', str: 67 },
  { name: 'Indy Eleven', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Lexington SC', div: 2, country: 'US', state: '', cont: 'NA', str: 69 },
  { name: 'Loudoun United', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'Louisville City', div: 2, country: 'US', state: '', cont: 'NA', str: 67 },
  { name: 'Memphis 901', div: 2, country: 'US', state: '', cont: 'NA', str: 68 },
  { name: 'Miami FC', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Monterey Bay', div: 2, country: 'US', state: '', cont: 'NA', str: 70 },
  { name: 'New Mexico United', div: 2, country: 'US', state: '', cont: 'NA', str: 70 },
  { name: 'North Carolina FC', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Oakland Roots', div: 2, country: 'US', state: '', cont: 'NA', str: 70 },
  { name: 'Orange County SC', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Phoenix Rising', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Pittsburgh Riverhounds', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'Rhode Island FC', div: 2, country: 'US', state: '', cont: 'NA', str: 66 },
  { name: 'Sacramento Republic', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'San Antonio FC', div: 2, country: 'US', state: '', cont: 'NA', str: 70 },
  { name: 'Tampa Bay Rowdies', div: 2, country: 'US', state: '', cont: 'NA', str: 65 },
  { name: 'Las Vegas Lights', div: 2, country: 'US', state: '', cont: 'NA', str: 69 },
  { name: 'AV Alta FC', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Athletic Club Boise', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },
  { name: 'Charlotte Independence', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },
  { name: 'Corpus Christi FC', div: 3, country: 'US', state: '', cont: 'NA', str: 55 },
  { name: 'FC Naples', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },
  { name: 'Forward Madison', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Fort Wayne FC', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Greenville Triumph', div: 3, country: 'US', state: '', cont: 'NA', str: 60 },
  { name: 'New York Cosmos', div: 3, country: 'US', state: '', cont: 'NA', str: 60 },
  { name: 'One Knoxville', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Portland Hearts of Pine', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },
  { name: 'Richmond Kickers', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Sarasota Paradise', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Spokane Velocity', div: 3, country: 'US', state: '', cont: 'NA', str: 57 },
  { name: 'Union Omaha', div: 3, country: 'US', state: '', cont: 'NA', str: 60 },
  { name: 'Westchester SC', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },
  { name: 'Chattanooga Red Wolves', div: 3, country: 'US', state: '', cont: 'NA', str: 59 },

  // ITÁLIA
  { name: 'Atalanta', div: 1, country: 'IT', state: '', cont: 'EU', str: 88 },
  { name: 'Bologna', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Cagliari', div: 1, country: 'IT', state: '', cont: 'EU', str: 85 },
  { name: 'Como', div: 1, country: 'IT', state: '', cont: 'EU', str: 87 },
  { name: 'Cremonese', div: 1, country: 'IT', state: '', cont: 'EU', str: 88 },
  { name: 'Fiorentina', div: 1, country: 'IT', state: '', cont: 'EU', str: 85 },
  { name: 'Genoa', div: 1, country: 'IT', state: '', cont: 'EU', str: 88 },
  { name: 'Hellas Verona', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Inter', div: 1, country: 'IT', state: '', cont: 'EU', str: 87 },
  { name: 'Juventus', div: 1, country: 'IT', state: '', cont: 'EU', str: 89 },
  { name: 'Lazio', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Lecce', div: 1, country: 'IT', state: '', cont: 'EU', str: 87 },
  { name: 'Milan', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Napoli', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Parma', div: 1, country: 'IT', state: '', cont: 'EU', str: 85 },
  { name: 'Pisa', div: 1, country: 'IT', state: '', cont: 'EU', str: 85 },
  { name: 'Roma', div: 1, country: 'IT', state: '', cont: 'EU', str: 90 },
  { name: 'Sassuolo', div: 1, country: 'IT', state: '', cont: 'EU', str: 89 },
  { name: 'Torino', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Udinese', div: 1, country: 'IT', state: '', cont: 'EU', str: 86 },
  { name: 'Avellino', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Bari', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Carrarese', div: 2, country: 'IT', state: '', cont: 'EU', str: 78 },
  { name: 'Catanzaro', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Cesena', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Empoli', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Frosinone', div: 2, country: 'IT', state: '', cont: 'EU', str: 78 },
  { name: 'Juve Stabia', div: 2, country: 'IT', state: '', cont: 'EU', str: 80 },
  { name: 'Mantova', div: 2, country: 'IT', state: '', cont: 'EU', str: 76 },
  { name: 'Modena', div: 2, country: 'IT', state: '', cont: 'EU', str: 80 },
  { name: 'Monza', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Padova', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Palermo', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Pescara', div: 2, country: 'IT', state: '', cont: 'EU', str: 80 },
  { name: 'Reggiana', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Sampdoria', div: 2, country: 'IT', state: '', cont: 'EU', str: 75 },
  { name: 'Spezia', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Südtirol', div: 2, country: 'IT', state: '', cont: 'EU', str: 79 },
  { name: 'Virtus Entella', div: 2, country: 'IT', state: '', cont: 'EU', str: 77 },
  { name: 'Venezia', div: 2, country: 'IT', state: '', cont: 'EU', str: 78 },

  // FRANÇA
  { name: 'Paris Saint-Germain', div: 1, country: 'FR', state: '', cont: 'EU', str: 84 },
  { name: 'Olympique Marseille', div: 1, country: 'FR', state: '', cont: 'EU', str: 86 },
  { name: 'Olympique Lyon', div: 1, country: 'FR', state: '', cont: 'EU', str: 88 },
  { name: 'AS Monaco', div: 1, country: 'FR', state: '', cont: 'EU', str: 83 },
  { name: 'LOSC Lille', div: 1, country: 'FR', state: '', cont: 'EU', str: 84 },
  { name: 'OGC Nice', div: 1, country: 'FR', state: '', cont: 'EU', str: 83 },
  { name: 'RC Lens', div: 1, country: 'FR', state: '', cont: 'EU', str: 88 },
  { name: 'Stade Rennais', div: 1, country: 'FR', state: '', cont: 'EU', str: 83 },
  { name: 'Toulouse', div: 1, country: 'FR', state: '', cont: 'EU', str: 86 },
  { name: 'Strasbourg', div: 1, country: 'FR', state: '', cont: 'EU', str: 83 },
  { name: 'Brest', div: 1, country: 'FR', state: '', cont: 'EU', str: 84 },
  { name: 'Nantes', div: 1, country: 'FR', state: '', cont: 'EU', str: 87 },
  { name: 'Montpellier', div: 1, country: 'FR', state: '', cont: 'EU', str: 85 },
  { name: 'Le Havre', div: 1, country: 'FR', state: '', cont: 'EU', str: 83 },
  { name: 'Auxerre', div: 1, country: 'FR', state: '', cont: 'EU', str: 86 },
  { name: 'Paris FC', div: 1, country: 'FR', state: '', cont: 'EU', str: 86 },
  { name: 'Metz', div: 1, country: 'FR', state: '', cont: 'EU', str: 84 },
  { name: 'Saint-Étienne', div: 1, country: 'FR', state: '', cont: 'EU', str: 85 },
  { name: 'Troyes', div: 2, country: 'FR', state: '', cont: 'EU', str: 73 },
  { name: 'Reims', div: 2, country: 'FR', state: '', cont: 'EU', str: 77 },
  { name: 'Le Mans', div: 2, country: 'FR', state: '', cont: 'EU', str: 78 },
  { name: 'Red Star', div: 2, country: 'FR', state: '', cont: 'EU', str: 78 },
  { name: 'Nancy', div: 2, country: 'FR', state: '', cont: 'EU', str: 75 },
  { name: 'Clermont', div: 2, country: 'FR', state: '', cont: 'EU', str: 75 },
  { name: 'Rodez', div: 2, country: 'FR', state: '', cont: 'EU', str: 78 },
  { name: 'Amiens', div: 2, country: 'FR', state: '', cont: 'EU', str: 76 },
  { name: 'Dunkerque', div: 2, country: 'FR', state: '', cont: 'EU', str: 74 },
  { name: 'Laval', div: 2, country: 'FR', state: '', cont: 'EU', str: 78 },
  { name: 'Annecy', div: 2, country: 'FR', state: '', cont: 'EU', str: 77 },
  { name: 'Pau', div: 2, country: 'FR', state: '', cont: 'EU', str: 76 },
  { name: 'Grenoble', div: 2, country: 'FR', state: '', cont: 'EU', str: 75 },
  { name: 'Montpellier B', div: 2, country: 'FR', state: '', cont: 'EU', str: 73 },
  { name: 'Guingamp', div: 2, country: 'FR', state: '', cont: 'EU', str: 78 },
  { name: 'Bastia', div: 2, country: 'FR', state: '', cont: 'EU', str: 77 },
  { name: 'Boulogne', div: 2, country: 'FR', state: '', cont: 'EU', str: 75 },
  { name: 'Caen', div: 2, country: 'FR', state: '', cont: 'EU', str: 73 },

  // ALEMANHA
  { name: 'Bayern Munich', div: 1, country: 'DE', state: '', cont: 'EU', str: 86 },
  { name: 'Borussia Dortmund', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'Bayer Leverkusen', div: 1, country: 'DE', state: '', cont: 'EU', str: 85 },
  { name: 'RB Leipzig', div: 1, country: 'DE', state: '', cont: 'EU', str: 88 },
  { name: 'Eintracht Frankfurt', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'VfB Stuttgart', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'SC Freiburg', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'Werder Bremen', div: 1, country: 'DE', state: '', cont: 'EU', str: 86 },
  { name: 'Wolfsburg', div: 1, country: 'DE', state: '', cont: 'EU', str: 87 },
  { name: 'Mainz 05', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'Union Berlin', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'Borussia Mönchengladbach', div: 1, country: 'DE', state: '', cont: 'EU', str: 88 },
  { name: 'FC Augsburg', div: 1, country: 'DE', state: '', cont: 'EU', str: 87 },
  { name: 'FC Köln', div: 1, country: 'DE', state: '', cont: 'EU', str: 87 },
  { name: 'Hamburger SV', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'St. Pauli', div: 1, country: 'DE', state: '', cont: 'EU', str: 87 },
  { name: 'Heidenheim', div: 1, country: 'DE', state: '', cont: 'EU', str: 86 },
  { name: 'Hoffenheim', div: 1, country: 'DE', state: '', cont: 'EU', str: 89 },
  { name: 'Hertha Berlin', div: 2, country: 'DE', state: '', cont: 'EU', str: 78 },
  { name: 'Schalke 04', div: 2, country: 'DE', state: '', cont: 'EU', str: 80 },
  { name: 'Hannover 96', div: 2, country: 'DE', state: '', cont: 'EU', str: 75 },
  { name: 'Fortuna Düsseldorf', div: 2, country: 'DE', state: '', cont: 'EU', str: 79 },
  { name: 'Karlsruher SC', div: 2, country: 'DE', state: '', cont: 'EU', str: 77 },
  { name: 'Nürnberg', div: 2, country: 'DE', state: '', cont: 'EU', str: 80 },
  { name: 'Kaiserslautern', div: 2, country: 'DE', state: '', cont: 'EU', str: 77 },
  { name: 'Magdeburg', div: 2, country: 'DE', state: '', cont: 'EU', str: 75 },
  { name: 'Paderborn', div: 2, country: 'DE', state: '', cont: 'EU', str: 78 },
  { name: 'Greuther Fürth', div: 2, country: 'DE', state: '', cont: 'EU', str: 80 },
  { name: 'Darmstadt 98', div: 2, country: 'DE', state: '', cont: 'EU', str: 78 },
  { name: 'Bochum', div: 2, country: 'DE', state: '', cont: 'EU', str: 78 },
  { name: 'Holstein Kiel', div: 2, country: 'DE', state: '', cont: 'EU', str: 76 },
  { name: 'Arminia Bielefeld', div: 2, country: 'DE', state: '', cont: 'EU', str: 75 },
  { name: 'Dynamo Dresden', div: 2, country: 'DE', state: '', cont: 'EU', str: 78 },
  { name: 'Eintracht Braunschweig', div: 2, country: 'DE', state: '', cont: 'EU', str: 79 },
  { name: 'Preußen Münster', div: 2, country: 'DE', state: '', cont: 'EU', str: 77 },
  { name: 'Elversberg', div: 2, country: 'DE', state: '', cont: 'EU', str: 79 },
  { name: 'Alemannia Aachen', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: 'Erzgebirge Aue', div: 3, country: 'DE', state: '', cont: 'EU', str: 67 },
  { name: 'Energie Cottbus', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: 'MSV Duisburg', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Rot-Weiss Essen', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: '1860 Munich', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Saarbrücken', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: 'Osnabrück', div: 3, country: 'DE', state: '', cont: 'EU', str: 70 },
  { name: 'Sandhausen', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Jahn Regensburg', div: 3, country: 'DE', state: '', cont: 'EU', str: 67 },
  { name: 'Hansa Rostock', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Viktoria Köln', div: 3, country: 'DE', state: '', cont: 'EU', str: 67 },
  { name: 'Waldhof Mannheim', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: 'Wehen Wiesbaden', div: 3, country: 'DE', state: '', cont: 'EU', str: 65 },
  { name: 'TSV Havelse', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Schweinfurt', div: 3, country: 'DE', state: '', cont: 'EU', str: 65 },
  { name: 'Hoffenheim II', div: 3, country: 'DE', state: '', cont: 'EU', str: 70 },
  { name: 'Borussia Dortmund II', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },
  { name: 'Hannover 96 II', div: 3, country: 'DE', state: '', cont: 'EU', str: 66 },
  { name: 'Stuttgart II', div: 3, country: 'DE', state: '', cont: 'EU', str: 68 },

  // ESPANHA
  { name: 'Real Madrid', div: 1, country: 'ES', state: '', cont: 'EU', str: 90 },
  { name: 'Barcelona', div: 1, country: 'ES', state: '', cont: 'EU', str: 91 },
  { name: 'Atlético Madrid', div: 1, country: 'ES', state: '', cont: 'EU', str: 90 },
  { name: 'Athletic Club', div: 1, country: 'ES', state: '', cont: 'EU', str: 89 },
  { name: 'Real Sociedad', div: 1, country: 'ES', state: '', cont: 'EU', str: 91 },
  { name: 'Villarreal', div: 1, country: 'ES', state: '', cont: 'EU', str: 87 },
  { name: 'Real Betis', div: 1, country: 'ES', state: '', cont: 'EU', str: 90 },
  { name: 'Sevilla', div: 1, country: 'ES', state: '', cont: 'EU', str: 90 },
  { name: 'Valencia', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Celta Vigo', div: 1, country: 'ES', state: '', cont: 'EU', str: 87 },
  { name: 'Osasuna', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Getafe', div: 1, country: 'ES', state: '', cont: 'EU', str: 90 },
  { name: 'Mallorca', div: 1, country: 'ES', state: '', cont: 'EU', str: 89 },
  { name: 'Girona', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Espanyol', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Rayo Vallecano', div: 1, country: 'ES', state: '', cont: 'EU', str: 91 },
  { name: 'Alavés', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Levante', div: 1, country: 'ES', state: '', cont: 'EU', str: 87 },
  { name: 'Oviedo', div: 1, country: 'ES', state: '', cont: 'EU', str: 91 },
  { name: 'Elche', div: 1, country: 'ES', state: '', cont: 'EU', str: 86 },
  { name: 'Almería', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Granada', div: 2, country: 'ES', state: '', cont: 'EU', str: 79 },
  { name: 'Cádiz', div: 2, country: 'ES', state: '', cont: 'EU', str: 79 },
  { name: 'Huesca', div: 2, country: 'ES', state: '', cont: 'EU', str: 81 },
  { name: 'Málaga', div: 2, country: 'ES', state: '', cont: 'EU', str: 80 },
  { name: 'Deportivo La Coruña', div: 2, country: 'ES', state: '', cont: 'EU', str: 78 },
  { name: 'Sporting Gijón', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Real Zaragoza', div: 2, country: 'ES', state: '', cont: 'EU', str: 76 },
  { name: 'Eibar', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Mirandés', div: 2, country: 'ES', state: '', cont: 'EU', str: 80 },
  { name: 'Racing Santander', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Burgos', div: 2, country: 'ES', state: '', cont: 'EU', str: 81 },
  { name: 'Castellón', div: 2, country: 'ES', state: '', cont: 'EU', str: 79 },
  { name: 'Córdoba', div: 2, country: 'ES', state: '', cont: 'EU', str: 78 },
  { name: 'Albacete', div: 2, country: 'ES', state: '', cont: 'EU', str: 80 },
  { name: 'Tenerife', div: 2, country: 'ES', state: '', cont: 'EU', str: 76 },
  { name: 'Leganés', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Las Palmas', div: 2, country: 'ES', state: '', cont: 'EU', str: 80 },
  { name: 'Valladolid', div: 2, country: 'ES', state: '', cont: 'EU', str: 77 },
  { name: 'Ceuta', div: 2, country: 'ES', state: '', cont: 'EU', str: 76 },
  { name: 'Andorra', div: 2, country: 'ES', state: '', cont: 'EU', str: 81 },
  { name: 'Cultural Leonesa', div: 2, country: 'ES', state: '', cont: 'EU', str: 79 },

];
